<a href="https://colab.research.google.com/github/law850/data-analytics-portfolio/blob/main/Merging_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Merging DataFrames:
# Create two DataFrames:
#df1 = pd.DataFrame({
#    'ID': [1, 2, 3],
 #   'Name': ['Alice', 'Bob', 'Charlie']
#})
#df2 = pd.DataFrame({
#   'ID': [2, 3, 4],
#'Salary': [70000, 80000, 90000]
#})
#• Merge the two DataFrames on the ID column using an inner join.
import pandas as pd

# 1. Create the first DataFrame (df1)
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# 2. Create the second DataFrame (df2)
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Salary': [70000, 80000, 90000]
})

# 3. Merge the two DataFrames on the 'ID' column using an inner join
merged_df = pd.merge(df1, df2, on='ID', how='inner')

# 4. Display the result
print("DataFrame 1:")
display(df1)
print("\nDataFrame 2:")
display(df2)
print("\nMerged DataFrame (Inner Join):")
display(merged_df)

DataFrame 1:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

DataFrame 2:

   ID  Salary
0   2   70000
1   3   80000
2   4   90000

Merged DataFrame (Inner Join):

   ID     Name  Salary
0   2      Bob   70000
1   3  Charlie   80000

In [3]:
import pandas as pd

# 1. Create the "Customers" table (from the CRM system)
customers_df = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104],
    'CustomerName': ['Alice Smith', 'Bob Jones', 'Charlie Brown', 'Diana Prince'],
    'Email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', 'diana@email.com']
})

# 2. Create the "Orders" table (from the Sales system)
orders_df = pd.DataFrame({
    'OrderID': ['ORD-001', 'ORD-002', 'ORD-003', 'ORD-004'],
    'CustomerID': [102, 103, 105, 101], # Notice 104 didn't order, and 105 is a guest checkout
    'OrderAmount': [150.00, 200.50, 75.25, 300.00]
})

# 3. Perform the Inner Join
# We merge on 'CustomerID' because that is the common column (the key) in both tables.
customer_orders = pd.merge(customers_df, orders_df, on='CustomerID', how='inner')

# 4. Display the results
print("--- Customers Table ---")
display(customers_df)
print("\n--- Orders Table ---")
display(orders_df)
print("\n--- Merged Table (Inner Join) ---")
display(customer_orders)

--- Customers Table ---

   CustomerID   CustomerName              Email
0         101    Alice Smith    alice@email.com
1         102      Bob Jones      bob@email.com
2         103  Charlie Brown  charlie@email.com
3         104   Diana Prince    diana@email.com

--- Orders Table ---

   OrderID  CustomerID  OrderAmount
0  ORD-001         102       150.00
1  ORD-002         103       200.50
2  ORD-003         105        75.25
3  ORD-004         101       300.00

--- Merged Table (Inner Join) ---

   CustomerID   CustomerName              Email  OrderID  OrderAmount
0         101    Alice Smith    alice@email.com  ORD-004        300.0
1         102      Bob Jones      bob@email.com  ORD-001        150.0
2         103  Charlie Brown  charlie@email.com  ORD-002        200.5

In [4]:
import pandas as pd

# 1. Create the "Employees" table (from the HR database)
employees_df = pd.DataFrame({
    'EmpID': [201, 202, 203, 204, 205],
    'Name': ['Sarah', 'Mike', 'Jessica', 'David', 'Emily'],
    'Department': ['Sales', 'Engineering', 'Sales', 'Marketing', 'Engineering']
})

# 2. Create the "Performance" table (from the quarterly review system)
performance_df = pd.DataFrame({
    'EmpID': [202, 203, 205, 206], # 201 and 204 are missing (maybe they are new hires)
    'Performance_Score': [85, 92, 78, 88], # 206 is a contractor not in the HR table
    'Review_Date': ['2023-10-01', '2023-10-02', '2023-10-01', '2023-10-03']
})

# 3. Perform the Inner Join
# We merge on 'EmpID' because it is the unique identifier in both tables.
performance_review = pd.merge(employees_df, performance_df, on='EmpID', how='inner')

# 4. Display the results
print("--- Employees Table ---")
display(employees_df)
print("\n--- Performance Table ---")
display(performance_df)
print("\n--- Merged Table (Inner Join) ---")
display(performance_review)

--- Employees Table ---

   EmpID     Name   Department
0    201    Sarah        Sales
1    202     Mike  Engineering
2    203  Jessica        Sales
3    204    David    Marketing
4    205    Emily  Engineering

--- Performance Table ---

   EmpID  Performance_Score Review_Date
0    202                 85  2023-10-01
1    203                 92  2023-10-02
2    205                 78  2023-10-01
3    206                 88  2023-10-03

--- Merged Table (Inner Join) ---

   EmpID     Name   Department  Performance_Score Review_Date
0    202     Mike  Engineering                 85  2023-10-01
1    203  Jessica        Sales                 92  2023-10-02
2    205    Emily  Engineering                 78  2023-10-01

In [5]:
import pandas as pd

# 1. Create the "Products" table
products_df = pd.DataFrame({
    'ProductID': ['P01', 'P02', 'P03', 'P04', 'P05'],
    'ProductName': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories', 'Accessories'],
    'UnitPrice': [1200.00, 25.00, 300.00, 75.00, 50.00]
})

# 2. Create the "Transactions" table
transactions_df = pd.DataFrame({
    'TransactionID': ['T001', 'T002', 'T003', 'T004', 'T005', 'T006'],
    'ProductID': ['P01', 'P02', 'P01', 'P03', 'P05', 'P06'], # P06 is a new product not in our catalog
    'Quantity': [2, 5, 1, 3, 4, 2]
})

# 3. Merge the two tables on 'ProductID' using an inner join
sales_df = pd.merge(transactions_df, products_df, on='ProductID', how='inner')

# 4. Create a new column for Total Revenue
sales_df['Total_Revenue'] = sales_df['Quantity'] * sales_df['UnitPrice']

# 5. Display the merged table
print("--- Merged Sales Table ---")
display(sales_df)

# 6. Group by Category and sum the revenue
category_revenue = sales_df.groupby('Category')['Total_Revenue'].sum().reset_index()

print("\n--- Total Revenue by Category ---")
display(category_revenue)

--- Merged Sales Table ---

,TransactionID,ProductID,Quantity,ProductName,Category,UnitPrice,Total_Revenue
0,T001,P01,2,Laptop,Electronics,1200.0,2400.0
1,T002,P02,5,Mouse,Accessories,25.0,125.0
2,T003,P01,1,Laptop,Electronics,1200.0,1200.0
3,T004,P03,3,Monitor,Electronics,300.0,900.0
4,T005,P05,4,Webcam,Accessories,50.0,200.0

--- Total Revenue by Category ---

      Category  Total_Revenue
0  Accessories          325.0
1  Electronics         4500.0